### PR TITLE
add member registration deploy yaml

### PR DESCRIPTION
**Pull request by julian9499**

### CODE REVIEW

**Review by Fastjur — APPROVED** [review]
I see no issues with these files, I am not sure if more actions are required from our side to make this work.

**Comment by Fastjur** [comment]
Though I do think you need an `ingress.yaml` file right?

**Comment by julian9499** [comment]
Added an ingress config update

**Review by Fastjur — APPROVED** [review]

**Comment by julian9499** [comment]
:shipit:

**Pull request merged**
